(()=>{'use strict';
const $=s=>document.querySelector(s), machine=$('#machineCanvas'), battle=$('#battleCanvas'),ctx=machine.getContext('2d'),art=battle.getContext('2d');
const MW=420,MH=340,LEFT=12,RIGHT=408,FLOOR=326,STEP=1/120,CHUTE=84;
const engine=ClawPhysics.create({left:LEFT,right:RIGHT,floor:FLOOR,chuteRight:CHUTE,dividerTop:145});
let delivered=[],totals={damage:0,block:0,heal:0,coins:0},contactInfo={},lastDelivery=0,gripCount=0;
let run,claw,balls=[],effects=[],floaters=[],phase='aim',phaseTime=0,clock=0,last=0,accumulator=0,paused=false,modalMode='',leftHeld=false,rightHeld=false,aimTarget=null,shake=0,battlePulse=0,enemyPulse=0,combo=0,comboTime=0,best=0;
try{best=Number(localStorage.getItem('clawbound-best'))||0}catch{}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),rand=(a,b)=>a+Math.random()*(b-a),lerp=(a,b,t)=>a+(b-a)*t;
const TYPES={sword:{name:'Sword',color:'#ff9b88',rim:'#ffe2c4',dark:'#743948',damage:4},shield:{name:'Shield',color:'#81d7e6',rim:'#ccf8f2',dark:'#225a73',block:4},heart:{name:'Heart',color:'#f292bb',rim:'#ffdbdf',dark:'#7f385d',heal:3},spark:{name:'Spark',color:'#b9a0f1',rim:'#e9deff',dark:'#58427c',damage:6},coin:{name:'Coin',color:'#f3cd76',rim:'#fff0bc',dark:'#89613b',coins:2},stone:{name:'Scrap',color:'#91acb8',rim:'#ccdae0',dark:'#405a70',damage:1}};
const weighted=['sword','sword','sword','sword','shield','shield','heart','spark','coin','stone','stone'];
const UPGRADES=[
{id:'size',mark:'↔',name:'Bigger claws',desc:'Wider physical jaws. Scoop a larger cluster.',apply:()=>{run.size++;run.capacity=Math.min(10,run.capacity+1)}},
{id:'capacity',mark:'⊞',name:'Rubber grips',desc:'More jaw friction. Help loose items stay in the scoop.',apply:()=>{run.grip=Math.min(1.8,run.grip+.25);run.capacity++}},
{id:'blade',mark:'✦',name:'Sharp edges',desc:'Every sword deals 2 more damage.',apply:()=>run.blade+=2},
{id:'block',mark:'◇',name:'Force field',desc:'Every shield gives 2 more block.',apply:()=>run.block+=2},
{id:'combo',mark:'×',name:'Big haul bonus',desc:'Collect 4+ items to deal 5 extra damage.',apply:()=>run.haul+=5},
{id:'battery',mark:'ϟ',name:'Spare battery',desc:'One extra drop on every floor.',apply:()=>run.extraDrops++},
{id:'repair',mark:'+',name:'Fresh plating',desc:'+8 maximum health. Restore 12 health now.',apply:()=>{run.maxHp+=8;run.hp=Math.min(run.maxHp,run.hp+12)}},
{id:'spark',mark:'⌁',name:'Overcharged',desc:'Every spark deals 3 more damage.',apply:()=>run.spark+=3}
];
let audio=null,muted=false;
try{muted=localStorage.getItem('clawbound-muted')==='true'}catch{}
function sound(kind,count=0){if(muted||document.hidden)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const tone=(freq,end,length,volume=.045,wave='sine',delay=0)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type=wave;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(end,t+length);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+length);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+length+.02)};if(kind==='drop')tone(130,78,.35,.025,'triangle');if(kind==='grip'){tone(240,100,.075,.035,'square');tone(160,90,.09,.025,'triangle',.08)}if(kind==='release')tone(270,430,.13,.025);if(kind==='collect'){let f=420*Math.pow(1.12,Math.min(count,10));tone(f,f*1.5,.19,.045);tone(f*2,f*2,.23,.018,'sine',.05)}if(kind==='hit')tone(170,52,.18,.045,'triangle')}catch{}}
function toggleSound(){muted=!muted;try{localStorage.setItem('clawbound-muted',String(muted))}catch{}$('#sound').textContent=muted?'♩':'♪';$('#sound').setAttribute('aria-label',muted?'Enable sound':'Mute sound');$('#sound').setAttribute('aria-pressed',String(!muted));if(!muted)sound('collect',1)}
function message(text){$('#status').textContent=text}
function updateUI(){
$('#coins').textContent=run.coins;$('#floor').textContent='FLOOR '+String(run.floor).padStart(2,'0');$('#zone').textContent=run.floor===10?'THE FINAL VAULT':run.floor%5===0?'BOSS CHAMBER':run.floor<5?'MOSSY OUTPOST':'CRYSTAL DEPTHS';
$('#heroHp').textContent=`${run.hp}/${run.maxHp}`;$('#heroBar').style.width=(100*run.hp/run.maxHp)+'%';$('#enemyHp').textContent=`${Math.max(0,run.enemy.hp)}/${run.enemy.maxHp}`;$('#enemyBar').style.width=(100*Math.max(0,run.enemy.hp)/run.enemy.maxHp)+'%';$('#enemyName').textContent=run.enemy.name;
$('#shield').textContent=`◇ ${run.shield} BLOCK`;$('#intent').textContent=`Next attack · ${run.enemy.attack}`;$('#drops').textContent=run.drops;$('#drop').disabled=phase!=='aim'||paused;
$('#dropLabel').textContent=paused?'PAUSED':{aim:'GRAB',down:'LOWERING',close:'SCOOPING',up:'NICE CATCH',carry:'DELIVERING',release:'LOOT!',resolve:'YOUR TURN',enemy:'INCOMING',return:'RETURNING',reward:'FLOOR CLEAR',over:'RUN COMPLETE'}[phase]||'GRAB';
$('#clawLabel').textContent=run.size>=2?'MEGA CLAW':run.size?'WIDE CLAW':'STANDARD CLAW';$('#load').textContent=claw.held.length+' IN SCOOP';$('#capacity').setAttribute('aria-label',`Approximate scoop size: ${run.capacity}`);$('#capacity').innerHTML=Array.from({length:run.capacity},(_,i)=>`<i class="${i<claw.held.length?'loaded':''}"></i>`).join('');
$('#routeDots').innerHTML=Array.from({length:10},(_,i)=>`<i class="route-dot ${i+1<run.floor?'done':i+1===run.floor?'current':''}"></i>`).join('');
$('.hint').textContent=`DRAG TO AIM · HOLD ARROWS TO MOVE · DELIVER ITEMS INTO THE LEFT CHUTE`;
$('#inventory').replaceChildren();Object.entries(run.relics).slice(-3).forEach(([id,count])=>{const u=UPGRADES.find(u=>u.id===id);let el=document.createElement('span');el.className='relic-tag';el.textContent=`${u.mark} ${u.name}${count>1?' ×'+count:''}`;$('#inventory').append(el)});
}
function newBall(x,y,type){return {x,y,oldX:x,oldY:y,vx:rand(-5,5),vy:0,r:12.8+Math.random()*1.5,type,angle:rand(-.5,.5),spin:rand(-1,1),held:false,alive:true}}
function fillPile(){balls=[];for(let row=0;row<6;row++)for(let col=0;col<10-(row%2);col++){let type=weighted[Math.floor(Math.random()*weighted.length)];balls.push(newBall(108+col*29+(row%2)*14.5+rand(-1,1),FLOOR-15-row*25.3,type))}for(let i=balls.length-12;i<balls.length;i+=3)balls[i].type=i%2?'sword':'spark';}
function setPhase(value){phase=value;phaseTime=0;updateUI()}
function startFloor(){const boss=run.floor%5===0;const maxHp=boss?50+run.floor*7:19+run.floor*7;run.enemy={name:boss?'THE VAULT KEEPER':['MOSS MUNCHER','CAVE CRITTER','GLOOM SPRITE','THORN GUARD'][(run.floor-1)%4],hp:maxHp,maxHp,attack:3+Math.floor(run.floor*.85)+(boss?2:0),boss,kind:boss?4:(run.floor-1)%4};run.drops=6+run.extraDrops;run.shield=Math.min(run.shield,12);claw={x:210,y:48,open:1,held:[],prevX:210,prevY:48,depth:FLOOR-82,contactTime:0};delivered=[];totals={damage:0,block:0,heal:0,coins:0};gripCount=0;engine.reset(jawSegments());effects=[];floaters=[];combo=0;leftHeld=rightHeld=false;aimTarget=null;fillPile();for(let i=0;i<100;i++)physics(STEP);setPhase('aim');message('Aim over the pile. Deliver your catch into the left chute.');}
function newRun(){closeModal();run={floor:1,hp:40,maxHp:40,shield:0,coins:0,size:0,capacity:5,blade:0,block:0,spark:0,haul:0,extraDrops:0,grip:.85,relics:{},totalCollected:0};startFloor()}
function halfWidth(){return 50+Math.min(run.size,3)*12}
function jawPoints(){let w=halfWidth(),closed=1-claw.open;return [-1,1].map(s=>[{x:claw.x+s*10,y:claw.y+6},{x:claw.x+s*w,y:claw.y+35},{x:claw.x+s*w*.82,y:claw.y+64},{x:claw.x+s*(w*.62*(1-closed)+5*closed),y:claw.y+77}])}
function jawSegments(){const segments=[];jawPoints().forEach((jaw,side)=>{for(let i=0;i<jaw.length-1;i++)segments.push({ax:jaw[i].x,ay:jaw[i].y,bx:jaw[i+1].x,by:jaw[i+1].y,r:3.5,id:`jaw-${side}-${i}`})});segments.push({ax:claw.x-10,ay:claw.y+3,bx:claw.x+10,by:claw.y+3,r:8,id:'hub'});return segments}
function drop(){if(phase!=='aim'||paused||run.drops<1)return;run.drops--;leftHeld=rightHeld=false;aimTarget=null;claw.open=1;claw.contactTime=0;claw.depth=FLOOR-82;claw.homeX=claw.x;delivered=[];totals={damage:0,block:0,heal:0,coins:0};lastDelivery=clock;gripCount=0;setPhase('down');sound('drop');message('The jaws will close when the hub reaches the pile.');}
function physics(dt){engine.config.jawFriction=run.grip||.85;contactInfo=engine.step(dt,balls,jawSegments());for(const b of balls){if(!b.alive)continue;if(b.x<CHUTE&&b.y-b.r>MH+6)collectBall(b)}if(['up','carry','release'].includes(phase)){claw.held=balls.filter(b=>b.alive&&Math.abs(b.x-claw.x)<halfWidth()+b.r&&b.y>claw.y+8&&b.y<claw.y+93);if(claw.held.length!==gripCount){gripCount=claw.held.length;updateUI()}}else claw.held=[];}
function capture(){// Feedback only: every token remains a free physical body.
claw.held=balls.filter(b=>b.alive&&Math.abs(b.x-claw.x)<halfWidth()&&b.y>claw.y+10&&b.y<claw.y+91);combo=claw.held.length;comboTime=1.7;message(combo?'Lifting carefully. Loose items can slip.':'Empty scoop. Try a denser cluster.');sound('grip');updateUI()}
function collectBall(b){b.alive=false;delivered.push(b);lastDelivery=clock;const t=TYPES[b.type],damage=(t.damage||0)+(b.type==='sword'?run.blade:0)+(b.type==='spark'?run.spark:0),block=(t.block||0)+(b.type==='shield'?run.block:0),heal=t.heal||0,coins=t.coins||0;totals.damage+=damage;totals.block+=block;totals.heal+=heal;totals.coins+=coins;run.totalCollected++;run.enemy.hp=Math.max(0,run.enemy.hp-damage);run.shield+=block;run.hp=Math.min(run.maxHp,run.hp+heal);run.coins+=coins;burst(48,MH-15,t.color,8);if(damage){float('-'+damage,315,77,t.color);enemyPulse=.4;shake=3}if(block)float('+'+block+' BLOCK',95,55,t.color);if(heal)float('+'+heal+' HP',90,83,t.color);if(coins)float('+'+coins+' COINS',210,46,t.color);sound('collect',delivered.length);updateUI()}
function burst(x,y,color,count=12){for(let i=0;i<count;i++)effects.push({x,y,vx:rand(-80,80),vy:rand(-120,20),life:rand(.35,.7),max:.7,color})}
function float(text,x,y,color){floaters.push({text,x,y,color,life:1.3})}
function resolveLoot(){if(delivered.length>=4&&run.haul){run.enemy.hp=Math.max(0,run.enemy.hp-run.haul);totals.damage+=run.haul;float('HAUL +'+run.haul,315,50,'#d8ff9f')}claw.held=[];combo=delivered.length;comboTime=1.5;const {damage,block,heal,coins}=totals;const summary=[damage?damage+' damage':'',block?block+' block':'',heal?heal+' healing':'',coins?coins+' coins':''].filter(Boolean).join(' · ');message(summary||'Nothing reached the chute. The enemy has an opening.');setPhase('resolve');}
function enemyAttack(){sound('hit');const blocked=Math.min(run.shield,run.enemy.attack),damage=run.enemy.attack-blocked;run.shield-=blocked;run.hp=Math.max(0,run.hp-damage);battlePulse=.65;shake=damage?7:2;float(damage?'-'+damage:'BLOCKED',95,66,damage?'#ff9d96':'#9fe9ef');message(blocked===run.enemy.attack?'Your shield absorbed the whole attack.':`Enemy hit for ${damage}${blocked?' · '+blocked+' blocked':''}.`);setPhase('enemy');}
function reward(){run.coins+=4+run.floor;if(run.floor>=10){gameOver(true);return}setPhase('reward');best=Math.max(best,run.floor);try{localStorage.setItem('clawbound-best',best)}catch{};const eligible=UPGRADES.filter(u=>!(u.id==='size'&&run.size>=3)&&!(u.id==='capacity'&&run.grip>=1.8));let shuffled=eligible.slice().sort(()=>Math.random()-.5);if(run.floor===1)shuffled=[UPGRADES[0],...shuffled.filter(u=>u.id!=='size')];const picks=shuffled.slice(0,3);openModal('reward','FLOOR CLEARED','Make it a bigger haul.',`Choose one upgrade. It stays with you for the rest of this run.`,picks.map(u=>({mark:u.mark,title:u.name,desc:u.desc,action:()=>{u.apply();run.relics[u.id]=(run.relics[u.id]||0)+1;closeModal();run.floor++;startFloor()}})));}
function gameOver(won){best=Math.max(best,run.floor);try{localStorage.setItem('clawbound-best',best)}catch{}setPhase('over');openModal('over',won?'VAULT CRACKED':'RUN COMPLETE',won?'One mighty machine.':'One more grab?',`Floor ${run.floor} · ${run.totalCollected} items collected · ${run.coins} coins<br>Best floor: ${best}`, [{mark:'↻',title:'Start a new run',desc:'A fresh pile. A new build.',action:newRun}]);}
function update(dt){clock+=dt;if(paused)return;phaseTime+=dt;claw.prevX=claw.x;claw.prevY=claw.y;
if(phase==='aim'){if(leftHeld||rightHeld){aimTarget=null;claw.x+=((rightHeld?1:0)-(leftHeld?1:0))*215*dt}else if(aimTarget!==null)claw.x+=clamp(aimTarget-claw.x,-320*dt,320*dt);claw.x=clamp(claw.x,CHUTE+halfWidth()+9,MW-halfWidth()-13);claw.open=lerp(claw.open,1,dt*8)}
if(phase==='return'){const goal=clamp(claw.homeX||210,CHUTE+halfWidth()+9,MW-halfWidth()-13);claw.x+=clamp(goal-claw.x,-190*dt,190*dt);if(Math.abs(goal-claw.x)<.1){setPhase('aim');message('Aim over the pile. Deliver your catch into the left chute.')}}
if(phase==='down'){claw.y=Math.min(claw.depth,claw.y+140*dt);claw.contactTime=(contactInfo.touchedIds||[]).includes('hub')?claw.contactTime+dt:0;if(claw.y>=claw.depth||claw.contactTime>.035){setPhase('close');sound('grip')}}
if(phase==='close'){claw.open=Math.max(0,1-phaseTime*1.5);if(phaseTime>.8){capture();setPhase('up')}}
if(phase==='up'){claw.y=Math.max(48,claw.y-95*dt);if(claw.y<=48)setPhase('carry')}
if(phase==='carry'){claw.x=Math.max(48,claw.x-110*dt);if(claw.x<=48){setPhase('release');sound('release')}}
if(phase==='release'){claw.open=Math.min(1,phaseTime*1.8);const pending=balls.some(b=>b.alive&&b.x<CHUTE&&b.y<MH+25);if(phaseTime>1.35&&!pending&&clock-lastDelivery>.25||phaseTime>4)resolveLoot()}
if(phase==='resolve'&&phaseTime>1.05){if(run.enemy.hp<=0)reward();else enemyAttack()}
if(phase==='enemy'&&phaseTime>.75){if(run.hp<=0)gameOver(false);else if(run.drops<=0){if(run.coins>=8){openModal('credit','OUT OF DROPS','One more chance?',`Spend 8 coins for 3 extra drops, or finish this run.`,[{mark:'ϟ',title:'Buy 3 drops · 8 coins',desc:`You have ${run.coins} coins`,action:()=>{run.coins-=8;run.drops=3;closeModal();setPhase('return');message('Three more drops. Make them count.')}},{mark:'↻',title:'New run',desc:'Start with a fresh machine.',action:newRun}])}else gameOver(false)}else{setPhase('return');message('Returning the claw to your last aim.')}}
physics(dt);comboTime=Math.max(0,comboTime-dt);shake*=Math.pow(.9,dt*60);battlePulse=Math.max(0,battlePulse-dt);enemyPulse=Math.max(0,enemyPulse-dt);for(const p of effects){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=250*dt;p.life-=dt}effects=effects.filter(p=>p.life>0);for(const f of floaters){f.y-=15*dt;f.life-=dt}floaters=floaters.filter(f=>f.life>0);
}
function rounded(g,x,y,w,h,r,fill,stroke){g.beginPath();g.roundRect(x,y,w,h,r);if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.stroke()}}
function ellipse(g,x,y,rx,ry,color){g.fillStyle=color;g.beginPath();g.ellipse(x,y,rx,ry,0,0,Math.PI*2);g.fill()}
function line(g,pts,color,width){g.strokeStyle=color;g.lineWidth=width;g.lineCap='round';g.lineJoin='round';g.beginPath();pts.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.stroke()}
function icon(g,type,x,y,r){g.save();g.translate(x,y);g.scale(r/14,r/14);g.lineWidth=2;g.lineCap='round';g.lineJoin='round';g.strokeStyle=TYPES[type].dark;g.fillStyle=TYPES[type].dark;g.beginPath();if(type==='sword'){g.moveTo(-5,6);g.lineTo(5,-7);g.lineTo(8,-8);g.lineTo(7,-4);g.lineTo(-3,7);g.stroke();g.beginPath();g.moveTo(-7,2);g.lineTo(1,8);g.stroke();g.beginPath();g.moveTo(-4,6);g.lineTo(-7,9);g.stroke()}else if(type==='shield'){g.moveTo(0,-8);g.lineTo(7,-5);g.lineTo(6,2);g.quadraticCurveTo(4,6,0,9);g.quadraticCurveTo(-5,6,-6,2);g.lineTo(-7,-5);g.closePath();g.fill();g.strokeStyle=TYPES[type].rim;g.beginPath();g.moveTo(0,-4);g.lineTo(0,4);g.stroke()}else if(type==='heart'){g.moveTo(0,7);g.bezierCurveTo(-15,-2,-5,-13,0,-5);g.bezierCurveTo(5,-13,15,-2,0,7);g.fill()}else if(type==='spark'){g.moveTo(2,-9);g.lineTo(-7,2);g.lineTo(-1,2);g.lineTo(-3,10);g.lineTo(8,-2);g.lineTo(2,-2);g.closePath();g.fill()}else if(type==='coin'){g.arc(0,0,7,0,Math.PI*2);g.stroke();g.beginPath();g.moveTo(0,-4);g.lineTo(0,4);g.stroke()}else{rounded(g,-5,-5,10,10,2,TYPES[type].dark);g.fillStyle=TYPES[type].rim;g.fillRect(-2,-2,4,4)}g.restore()}
function drawBall(g,b){const t=TYPES[b.type];ellipse(g,b.x+1,b.y+2,b.r,b.r,'#0005');let grad=g.createLinearGradient(b.x,b.y-b.r,b.x,b.y+b.r);grad.addColorStop(0,t.rim);grad.addColorStop(.23,t.color);grad.addColorStop(1,t.color);ellipse(g,b.x,b.y,b.r,b.r,grad);g.strokeStyle=t.rim;g.lineWidth=1;g.beginPath();g.arc(b.x,b.y,b.r-.5,0,Math.PI*2);g.stroke();g.save();g.translate(b.x,b.y);g.rotate(b.angle);icon(g,b.type,0,0,b.r*.86);g.restore();ellipse(g,b.x-b.r*.37,b.y-b.r*.46,b.r*.22,b.r*.12,'#ffffff6a')}
function drawMachine(){const g=ctx;g.clearRect(0,0,MW,MH);const bg=g.createLinearGradient(0,0,0,MH);bg.addColorStop(0,'#172a3b');bg.addColorStop(1,'#102333');g.fillStyle=bg;g.fillRect(0,0,MW,MH);g.strokeStyle='#a2d5dc0a';g.lineWidth=1;for(let x=0;x<MW;x+=24){g.beginPath();g.moveTo(x,0);g.lineTo(x,MH);g.stroke()}for(let y=0;y<MH;y+=24){g.beginPath();g.moveTo(0,y);g.lineTo(MW,y);g.stroke()}rounded(g,LEFT,145,CHUTE-LEFT,MH-145,0,'#06111d');let chuteGlow=g.createLinearGradient(LEFT,0,CHUTE,0);chuteGlow.addColorStop(0,'#6bdabc10');chuteGlow.addColorStop(.5,'#91e89730');chuteGlow.addColorStop(1,'#6bdabc08');g.fillStyle=chuteGlow;g.fillRect(LEFT,145,CHUTE-LEFT,MH-145);g.font='800 10px system-ui';g.fillStyle='#baf27c';g.textAlign='center';g.fillText('PRIZE',48,173);for(let i=0;i<4;i++){let yy=192+i*38+(clock*20)%38;line(g,[{x:38,y:yy},{x:48,y:yy+7},{x:58,y:yy}],'#baf27c25',2)}line(g,[{x:CHUTE,y:145},{x:CHUTE,y:MH+10}],'#07151f',9);line(g,[{x:CHUTE,y:145},{x:CHUTE,y:MH+10}],'#819da8',4);ellipse(g,CHUTE,145,4,4,'#d6e7d0');
rounded(g,13,20,394,7,3,'#080f1b');rounded(g,13,20,394,2,1,'#7890a0');rounded(g,CHUTE,FLOOR,RIGHT-CHUTE+4,14,3,'#3d5367');g.fillStyle='#80949d';g.fillRect(CHUTE,FLOOR,RIGHT-CHUTE+4,2);for(let x=CHUTE+8;x<410;x+=18){g.fillStyle='#202f40';g.fillRect(x,FLOOR+5,8,3)}
if(phase==='aim'){g.save();g.setLineDash([3,6]);line(g,[{x:claw.x,y:claw.y+76},{x:claw.x,y:FLOOR-12}],'#c8f29b35',1);g.restore();ellipse(g,claw.x,FLOOR-8,halfWidth()*.9,6,'#b6ed7825')}
for(const b of balls)if(b.alive)drawBall(g,b);
const jaws=jawPoints();for(const jaw of jaws){line(g,jaw,'#091823',10);line(g,jaw,'#839ea7',7);line(g,jaw.map(p=>({x:p.x-1.2,y:p.y-1.2})),'#dceacb',3)}

line(g,[{x:claw.x,y:27},{x:claw.x,y:claw.y}],'#08141d',5);line(g,[{x:claw.x,y:27},{x:claw.x,y:claw.y}],'#879da8',2);rounded(g,claw.x-22,13,44,20,6,'#a5ce84','#d6eead');rounded(g,claw.x-12,17,24,5,2,'#486746');ellipse(g,claw.x-15,27,2,2,'#486746');ellipse(g,claw.x+15,27,2,2,'#486746');rounded(g,claw.x-16,claw.y-9,32,20,6,'#b1d28f','#e5f3c9');rounded(g,claw.x-6,claw.y-4,12,9,3,'#4a6951');ellipse(g,claw.x,claw.y,2,2,'#dafa8c');
for(const p of effects){g.globalAlpha=p.life/p.max;ellipse(g,p.x,p.y,2.4,2.4,p.color)}g.globalAlpha=1;
if(comboTime>0&&combo>0){g.save();g.globalAlpha=Math.min(1,comboTime*2);const text=combo>=4?'BIG HAUL! ×'+combo:'NICE! ×'+combo;g.font='900 16px system-ui';g.textAlign='center';g.shadowColor='#08131d';g.shadowBlur=8;g.fillStyle=combo>=4?'#d8ff9f':'#edf7e4';g.fillText(text,MW/2,Math.max(67,claw.y-19));g.restore()}
g.textAlign='left';g.fillStyle='#ffffff04';g.beginPath();g.moveTo(20,0);g.lineTo(83,0);g.lineTo(173,MH);g.lineTo(141,MH);g.fill();
}
function robot(g,x,y,s,t){g.save();g.translate(x,y);g.scale(s,s);const bob=Math.sin(t*2.5)*1.6;g.translate(0,bob);ellipse(g,0,40,27,5,'#06191777');line(g,[{x:-12,y:23},{x:-16,y:35}],'#72867c',11);line(g,[{x:12,y:23},{x:15,y:35}],'#72867c',11);rounded(g,-25,31,20,10,4,'#c4d2b1');rounded(g,6,31,20,10,4,'#c4d2b1');rounded(g,-20,-6,40,36,9,'#7d9973','#cecea8');rounded(g,-12,3,24,19,5,'#a5bd87');ellipse(g,0,12,7,7,'#3d6254');ellipse(g,0,12,4,4,'#c0f993');line(g,[{x:-21,y:0},{x:-28,y:13},{x:-26,y:22}],'#9aab8d',10);line(g,[{x:21,y:0},{x:31,y:10},{x:30,y:20}],'#9aab8d',10);ellipse(g,-26,22,6,6,'#d1d8b3');ellipse(g,30,20,6,6,'#d1d8b3');line(g,[{x:0,y:-31},{x:3,y:-45}],'#93ab8a',3);ellipse(g,3,-45,4,4,'#dcf9a0');rounded(g,-26,-37,52,34,10,'#c8d8ad','#e8f0cd');rounded(g,-21,-29,42,21,7,'#213b3d');rounded(g,-15,-24,10,8,3,'#c2f59d');rounded(g,6,-24,10,8,3,'#c2f59d');line(g,[{x:-4,y:-12},{x:3,y:-12}],'#74ab8b',2);rounded(g,-33,-28,8,19,3,'#839d78');rounded(g,25,-28,8,19,3,'#839d78');g.restore()}
function monster(g,x,y,s,t,kind){g.save();g.translate(x,y);g.scale(s,s);let bob=Math.sin(t*3)*2;g.translate(0,bob);ellipse(g,0,39,31,6,'#06191777');const boss=kind===4;const colors=[['#99bc78','#5d8555'],['#daa879','#9d665a'],['#b49bcf','#665b94'],['#8eb8a8','#4e847d'],['#9aabd0','#586581']][kind];if(boss){rounded(g,-30,-35,60,72,10,colors[1],'#c3d1ec');rounded(g,-22,-28,44,42,7,colors[0]);line(g,[{x:-32,y:-21},{x:-45,y:6},{x:-37,y:30}],colors[0],14);line(g,[{x:32,y:-21},{x:45,y:6},{x:37,y:30}],colors[0],14);for(let i=-1;i<=1;i++){g.fillStyle='#e2c988';g.beginPath();g.moveTo(i*15-7,-34);g.lineTo(i*15,-50);g.lineTo(i*15+7,-34);g.fill()}rounded(g,-22,26,18,15,4,colors[0]);rounded(g,5,26,18,15,4,colors[0]);}else{g.fillStyle=colors[1];g.beginPath();g.moveTo(-30,29);g.bezierCurveTo(-38,-10,-20,-31,0,-31);g.bezierCurveTo(25,-31,35,-3,32,29);g.quadraticCurveTo(10,43,-30,29);g.fill();ellipse(g,-4,0,27,28,colors[0]);ellipse(g,-20,32,12,6,colors[0]);ellipse(g,20,32,12,6,colors[0]);if(kind===0||kind===3){g.fillStyle='#b2d88c';g.beginPath();g.moveTo(-4,-29);g.quadraticCurveTo(-29,-51,-28,-24);g.quadraticCurveTo(-14,-19,-4,-29);g.fill();g.beginPath();g.moveTo(0,-29);g.quadraticCurveTo(20,-56,25,-35);g.quadraticCurveTo(22,-25,0,-29);g.fill()}else{g.fillStyle=colors[1];g.beginPath();g.moveTo(-23,-17);g.lineTo(-32,-40);g.lineTo(-4,-29);g.fill();g.beginPath();g.moveTo(16,-23);g.lineTo(34,-40);g.lineTo(32,-6);g.fill()}}
rounded(g,-20,-13,15,14,5,'#21313a');rounded(g,6,-13,15,14,5,'#21313a');ellipse(g,-10,-6,3,3,'#ffe6a3');ellipse(g,16,-6,3,3,'#ffe6a3');line(g,[{x:-8,y:12},{x:0,y:15},{x:9,y:11}],'#30483f',3);g.fillStyle='#f1ebc5';g.beginPath();g.moveTo(-8,12);g.lineTo(-4,18);g.lineTo(-1,14);g.fill();g.restore()}
function drawBattle(){const g=art,BW=420,BH=180;g.clearRect(0,0,BW,BH);const grad=g.createLinearGradient(0,0,0,BH);grad.addColorStop(0,run.floor<5?'#2a4135':'#303451');grad.addColorStop(1,'#182a2c');g.fillStyle=grad;g.fillRect(0,0,BW,BH);g.fillStyle='#b7d39408';for(let i=0;i<8;i++){g.fillRect(i*62-20,20,23,115);g.beginPath();g.moveTo(i*62-28,24);g.lineTo(i*62+20,24);g.lineTo(i*62-3,-8);g.fill()}ellipse(g,210,151,210,27,'#365141');ellipse(g,210,160,210,23,'#213b33');for(let i=0;i<28;i++){let x=(i*71)%420,y=142+(i*13)%33;g.fillStyle=i%3?'#88a17122':'#c0d39632';g.fillRect(x,y,3+(i%4),2)}
for(let i=0;i<9;i++)ellipse(g,(i*53+clock*3)%420,53+(i*29)%75+Math.sin(clock+i)*3,1,1,'#d7eca744');
let heroX=101,enemyX=316;if(phase==='resolve'&&phaseTime<.45)heroX+=Math.sin(phaseTime/.45*Math.PI)*25;if(phase==='enemy'&&phaseTime<.35)enemyX-=Math.sin(phaseTime/.35*Math.PI)*25;g.save();if(shake>1)g.translate(Math.sin(clock*60)*shake*.25,0);robot(g,heroX,116,run.hp<=0?.85:.9,clock);monster(g,enemyX,117,run.enemy.boss?.96:.95,clock,run.enemy.kind);if(run.shield>0){g.strokeStyle='#7cdaea77';g.lineWidth=2;g.beginPath();g.ellipse(heroX,110,41,48,0,-1.3,1.3);g.stroke()}if(phase==='resolve'&&phaseTime<.45){const p=phaseTime/.45;ellipse(g,lerp(heroX+30,enemyX,p),109-Math.sin(p*Math.PI)*16,7,4,'#e4faa6');ellipse(g,lerp(heroX+17,enemyX-12,p),112-Math.sin(p*Math.PI)*16,4,2,'#e4faa677')}g.restore();for(const f of floaters){g.save();g.globalAlpha=clamp(f.life*2,0,1);g.font='900 18px system-ui';g.textAlign='center';g.lineWidth=4;g.strokeStyle='#16292e';g.strokeText(f.text,f.x,f.y);g.fillStyle=f.color;g.fillText(f.text,f.x,f.y);g.restore()}}
function resizeCanvas(canvas,g,w,h){const dpr=Math.min(window.devicePixelRatio||1,2);const width=Math.round(w*dpr),height=Math.round(h*dpr);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}g.setTransform(dpr,0,0,dpr,0,0)}
function render(){resizeCanvas(machine,ctx,MW,MH);resizeCanvas(battle,art,420,180);drawMachine();drawBattle()}
function frame(t){const dt=Math.min(.05,(t-last)/1000||STEP);last=t;accumulator+=dt;while(accumulator>=STEP){update(STEP);accumulator-=STEP}render();requestAnimationFrame(frame)}
function closeModal(){if($('#modal').open)$('#modal').close();paused=false;modalMode='';leftHeld=rightHeld=false;aimTarget=null;$('#pause').textContent='Ⅱ'}
function openModal(mode,eyebrow,title,copy,choices,extra=''){paused=true;modalMode=mode;leftHeld=rightHeld=false;aimTarget=null;$('#modalEyebrow').textContent=eyebrow;$('#modalTitle').textContent=title;$('#modalCopy').innerHTML=copy;$('#modalExtra').innerHTML=extra;$('#choices').replaceChildren();for(const choice of choices){const b=document.createElement('button');b.className='choice';b.innerHTML=`<span class="choice-mark">${choice.mark}</span><span><b>${choice.title}</b><small>${choice.desc||''}</small></span><span class="arrow">›</span>`;b.onclick=choice.action;$('#choices').append(b)}if(!$('#modal').open)$('#modal').showModal();updateUI()}
function help(){if(paused)return;openModal('help','HOW TO PLAY','Grab. Fight. Upgrade.','Move the claw with your finger or the arrow buttons. Press Grab to close the jaws around a cluster. Items can slip. Only items that fall through the left prize chute power your robot; the enemy attacks afterward.',[{mark:'✓',title:'Let’s grab',desc:'Shields carry over between attacks.',action:()=>{closeModal();updateUI()}}],`<div class="legend"><div class="legend-row"><span class="sample" style="background:#ff9b88;color:#743948">⚔</span>Sword · 4 damage per item</div><div class="legend-row"><span class="sample" style="background:#81d7e6;color:#225a73">◇</span>Shield · blocks 4 damage</div><div class="legend-row"><span class="sample" style="background:#f292bb;color:#7f385d">♥</span>Heart · restores 3 health</div><div class="legend-row"><span class="sample" style="background:#b9a0f1;color:#58427c">ϟ</span>Spark · 6 damage</div><div class="legend-row"><span class="sample" style="background:#f3cd76;color:#89613b">●</span>Coins · buy extra drops when you run out</div><div class="legend-row"><span class="sample" style="background:#91acb8;color:#405a70">▪</span>Scrap · 1 damage</div></div>`)}
function pause(){if(paused)return;openModal('pause','TAKE A BREATHER','Machine paused.','Your run is right where you left it.',[{mark:'▶',title:'Keep playing',desc:'Return to the machine.',action:()=>{closeModal();updateUI()}},{mark:'↻',title:'Restart run',desc:'Start again from floor 1.',action:newRun}])}
function hold(button,key){button.addEventListener('pointerdown',e=>{if(paused||phase!=='aim')return;e.preventDefault();button.setPointerCapture(e.pointerId);if(key==='left')leftHeld=true;else rightHeld=true;aimTarget=null});const stop=()=>{if(key==='left')leftHeld=false;else rightHeld=false};['pointerup','pointercancel','lostpointercapture'].forEach(ev=>button.addEventListener(ev,stop))}
hold($('#left'),'left');hold($('#right'),'right');let dragging=false;function aim(e){if(phase!=='aim'||paused)return;const rect=machine.getBoundingClientRect();aimTarget=clamp((e.clientX-rect.left)/rect.width*MW,CHUTE+halfWidth()+9,MW-halfWidth()-13)}machine.addEventListener('pointerdown',e=>{if(phase!=='aim'||paused)return;e.preventDefault();dragging=true;machine.setPointerCapture(e.pointerId);aim(e)});machine.addEventListener('pointermove',e=>{if(dragging)aim(e)});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>machine.addEventListener(ev,()=>dragging=false));$('#sound').onclick=toggleSound;$('#sound').textContent=muted?'♩':'♪';$('#sound').setAttribute('aria-label',muted?'Enable sound':'Mute sound');$('#drop').onclick=drop;$('#help').onclick=help;$('#pause').onclick=pause;$('#modal').addEventListener('cancel',e=>{e.preventDefault();if(modalMode==='help'||modalMode==='pause'){closeModal();updateUI()}});window.addEventListener('keydown',e=>{if(paused)return;if(['ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft'||e.code==='KeyA'){leftHeld=true;aimTarget=null}if(e.code==='ArrowRight'||e.code==='KeyD'){rightHeld=true;aimTarget=null}if(e.code==='Space'&&!e.repeat)drop();if(e.code==='Escape')pause()});window.addEventListener('keyup',e=>{if(e.code==='ArrowLeft'||e.code==='KeyA')leftHeld=false;if(e.code==='ArrowRight'||e.code==='KeyD')rightHeld=false});window.addEventListener('blur',()=>{leftHeld=rightHeld=false;dragging=false});document.addEventListener('visibilitychange',()=>{if(document.hidden){leftHeld=rightHeld=false;last=0;accumulator=0}});
newRun();requestAnimationFrame(frame);
})();
