/* Generated by scripts/build-offline.cjs. Install a complete revision atomically. */
'use strict';
const CACHE = 'clawbound-cc2fc84b448b72a3';
const FILES = [
  "index.html",
  "styles.css",
  "physics.js",
  "progression.js",
  "art.js",
  "loot.js",
  "game.js",
  "privacy.html",
  "manifest.webmanifest",
  "icon.svg",
  "assets/app-icon-1024.png",
  "assets/app-icon-192.png",
  "assets/app-icon-512.png",
  "assets/characters-v3.webp",
  "assets/vault-v3.webp"
];
const URLS = new Set(FILES.map(name => new URL(name, self.registration.scope).href));
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => Promise.all(FILES.map(async name => { const key = new URL(name, self.registration.scope); const fresh = new URL(key); fresh.searchParams.set('release', CACHE); const response = await fetch(new Request(fresh, {cache: 'reload'})); if (!response.ok) throw new Error('Missing release asset: ' + name); await cache.put(key, response); }))));
  // Leave the previous game running. Activate after its tabs have been closed.
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('clawbound-') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  url.search = '';
  if (event.request.mode === 'navigate' && (url.href === self.registration.scope || url.href === new URL('index.html', self.registration.scope).href)) {
    event.respondWith(caches.open(CACHE).then(cache => cache.match(new URL('index.html', self.registration.scope).href)).then(hit => hit || fetch(event.request)));
  } else if (URLS.has(url.href)) {
    event.respondWith(caches.open(CACHE).then(cache => cache.match(url.href)).then(hit => hit || fetch(event.request)));
  }
});
