'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const files = ['index.html', 'styles.css', 'physics.js', 'progression.js', 'art.js', 'loot.js', 'game.js', 'privacy.html', 'manifest.webmanifest', 'icon.svg'];
function assets(dir) {
  if (!fs.existsSync(path.join(root, dir))) return;
  for (const name of fs.readdirSync(path.join(root, dir)).sort()) {
    const rel = path.posix.join(dir, name);
    if (fs.statSync(path.join(root, rel)).isDirectory()) assets(rel);
    else if (!/\.(md|txt|map)$/i.test(name)) files.push(rel);
  }
}
assets('assets'); assets('fonts');
const hash = crypto.createHash('sha256');
for (const name of files) { hash.update(name); hash.update(fs.readFileSync(path.join(root, name))); }
const revision = hash.digest('hex').slice(0, 16);
const output = `/* Generated by scripts/build-offline.cjs. Install a complete revision atomically. */
'use strict';
const CACHE = 'clawbound-${revision}';
const FILES = ${JSON.stringify(files, null, 2)};
const URLS = new Set(FILES.map(name => new URL(name, self.registration.scope).href));
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => Promise.all(FILES.map(async name => { const key = new URL(name, self.registration.scope); const fresh = new URL(key); fresh.searchParams.set('release', CACHE); const response = await fetch(new Request(fresh, {cache: 'reload'})); if (!response.ok) throw new Error('Missing release asset: ' + name); await cache.put(key, response); }))));
  // Leave the previous game running. Activate after its tabs have been closed.
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('clawbound-') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  url.search = '';
  if (event.request.mode === 'navigate' && (url.href === self.registration.scope || url.href === new URL('index.html', self.registration.scope).href)) {
    event.respondWith(caches.open(CACHE).then(cache => cache.match(new URL('index.html', self.registration.scope).href)).then(hit => hit || fetch(event.request)));
  } else if (URLS.has(url.href)) {
    event.respondWith(caches.open(CACHE).then(cache => cache.match(url.href)).then(hit => hit || fetch(event.request)));
  }
});
`;
fs.writeFileSync(path.join(root, 'sw.js'), output);
console.log(`Offline revision ${revision}: ${files.length} files.`);
